package seo

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// RobotsConfig holds robots.txt generation configuration
type RobotsConfig struct {
	Enabled    bool         `yaml:"enabled" json:"enabled"`
	OutputDir  string       `yaml:"output_dir" json:"output_dir"`
	SitemapURL string       `yaml:"sitemap_url" json:"sitemap_url"`
	Rules      []RobotsRule `yaml:"rules" json:"rules"`
}

// RobotsRule represents a robots.txt rule for a specific user-agent
type RobotsRule struct {
	UserAgent  string   `yaml:"user_agent" json:"user_agent"`
	Allow      []string `yaml:"allow" json:"allow"`
	Disallow   []string `yaml:"disallow" json:"disallow"`
	CrawlDelay int      `yaml:"crawl_delay" json:"crawl_delay"`
}

// DefaultRobotsConfig returns default robots.txt configuration
func DefaultRobotsConfig() RobotsConfig {
	return RobotsConfig{
		Enabled:   false,
		OutputDir: ".",
		Rules: []RobotsRule{
			{
				UserAgent: "*",
				Allow:     []string{"/"},
				Disallow:  []string{"/admin/", "/api/", "/login"},
			},
			{
				UserAgent:  "Baiduspider",
				CrawlDelay: 5,
			},
			{
				UserAgent:  "Googlebot",
				CrawlDelay: 1,
			},
		},
	}
}

// RobotsGenerator generates robots.txt content
type RobotsGenerator struct {
	config RobotsConfig
}

// NewRobotsGenerator creates a new robots.txt generator
func NewRobotsGenerator(config RobotsConfig) *RobotsGenerator {
	return &RobotsGenerator{config: config}
}

// Generate generates robots.txt content
func (g *RobotsGenerator) Generate() string {
	var sb strings.Builder

	for i, rule := range g.config.Rules {
		if i > 0 {
			sb.WriteString("\n")
		}

		sb.WriteString(fmt.Sprintf("User-agent: %s\n", rule.UserAgent))

		for _, allow := range rule.Allow {
			sb.WriteString(fmt.Sprintf("Allow: %s\n", allow))
		}

		for _, disallow := range rule.Disallow {
			sb.WriteString(fmt.Sprintf("Disallow: %s\n", disallow))
		}

		if rule.CrawlDelay > 0 {
			sb.WriteString(fmt.Sprintf("Crawl-delay: %d\n", rule.CrawlDelay))
		}
	}

	// Add sitemap reference
	if g.config.SitemapURL != "" {
		sb.WriteString("\n")
		sb.WriteString(fmt.Sprintf("Sitemap: %s\n", g.config.SitemapURL))
	}

	return sb.String()
}

// WriteToFile writes robots.txt to a file
func (g *RobotsGenerator) WriteToFile(outputPath string) error {
	dir := filepath.Dir(outputPath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("create directory: %w", err)
	}

	content := g.Generate()
	return os.WriteFile(outputPath, []byte(content), 0644)
}

// GenerateWithTimestamp generates robots.txt with a comment timestamp
func (g *RobotsGenerator) GenerateWithTimestamp() string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("# Generated by PrerenderShield on %s\n", time.Now().UTC().Format(time.RFC3339)))
	sb.WriteString("# https://prerender.websitetool.cn\n\n")

	sb.WriteString(g.Generate())

	return sb.String()
}
