package seo

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestDefaultRobotsConfig(t *testing.T) {
	cfg := DefaultRobotsConfig()

	assert.False(t, cfg.Enabled)
	assert.Equal(t, ".", cfg.OutputDir)
	assert.Empty(t, cfg.SitemapURL)
	require.Len(t, cfg.Rules, 3)
	assert.Equal(t, "*", cfg.Rules[0].UserAgent)
	assert.Equal(t, []string{"/"}, cfg.Rules[0].Allow)
	assert.Equal(t, []string{"/admin/", "/api/", "/login"}, cfg.Rules[0].Disallow)
	assert.Equal(t, 5, cfg.Rules[1].CrawlDelay)
	assert.Equal(t, "Googlebot", cfg.Rules[2].UserAgent)
}

func TestRobotsGenerator_Generate(t *testing.T) {
	g := NewRobotsGenerator(RobotsConfig{
		Rules: []RobotsRule{
			{
				UserAgent:  "*",
				Allow:      []string{"/"},
				Disallow:   []string{"/admin/"},
				CrawlDelay: 2,
			},
			{
				UserAgent: "Baiduspider",
			},
		},
		SitemapURL: "https://example.com/sitemap.xml",
	})

	got := g.Generate()

	assert.Contains(t, got, "User-agent: *\n")
	assert.Contains(t, got, "Allow: /\n")
	assert.Contains(t, got, "Disallow: /admin/\n")
	assert.Contains(t, got, "Crawl-delay: 2\n")
	assert.Contains(t, got, "User-agent: Baiduspider\n")
	// 规则之间以空行分隔
	assert.Contains(t, got, "\n\n")
	// sitemap 引用
	assert.Contains(t, got, "\nSitemap: https://example.com/sitemap.xml\n")
}

func TestRobotsGenerator_Generate_NoSitemap(t *testing.T) {
	g := NewRobotsGenerator(RobotsConfig{
		Rules: []RobotsRule{{UserAgent: "*"}},
	})

	got := g.Generate()
	assert.False(t, strings.Contains(got, "Sitemap:"))
}

func TestRobotsGenerator_Generate_NoCrawlDelay(t *testing.T) {
	g := NewRobotsGenerator(RobotsConfig{
		Rules: []RobotsRule{{UserAgent: "*", CrawlDelay: 0}},
	})

	assert.NotContains(t, g.Generate(), "Crawl-delay:")
}

func TestRobotsGenerator_WriteToFile(t *testing.T) {
	dir := t.TempDir()
	outputPath := filepath.Join(dir, "nested", "robots.txt")

	g := NewRobotsGenerator(DefaultRobotsConfig())
	err := g.WriteToFile(outputPath)
	require.NoError(t, err)

	content, err := os.ReadFile(outputPath)
	require.NoError(t, err)
	assert.Contains(t, string(content), "User-agent: *")
}

func TestRobotsGenerator_WriteToFile_MkdirError(t *testing.T) {
	dir := t.TempDir()
	// 在目录位置放一个文件，使 MkdirAll 失败
	blocker := filepath.Join(dir, "blocker")
	require.NoError(t, os.WriteFile(blocker, []byte("x"), 0o644))

	g := NewRobotsGenerator(RobotsConfig{Rules: []RobotsRule{{UserAgent: "*"}}})
	err := g.WriteToFile(filepath.Join(blocker, "robots.txt"))
	require.Error(t, err)
	assert.Contains(t, err.Error(), "create directory")
}

func TestRobotsGenerator_GenerateWithTimestamp(t *testing.T) {
	g := NewRobotsGenerator(RobotsConfig{
		Rules:      []RobotsRule{{UserAgent: "*", Allow: []string{"/"}}},
		SitemapURL: "https://example.com/sitemap.xml",
	})

	got := g.GenerateWithTimestamp()

	assert.Contains(t, got, "# Generated by PrerenderShield on ")
	assert.Contains(t, got, "# https://prerender.websitetool.cn")
	assert.Contains(t, got, "User-agent: *")
	assert.Contains(t, got, "Sitemap: https://example.com/sitemap.xml")
}
