export interface Country {
  code: string;
  name: string;
  cnName: string;
}

export const COUNTRIES: Country[] = [
  { code: 'CN', name: 'China', cnName: '中国' },
  { code: 'US', name: 'United States', cnName: '美国' },
  { code: 'GB', name: 'United Kingdom', cnName: '英国' },
  { code: 'JP', name: 'Japan', cnName: '日本' },
  { code: 'KR', name: 'South Korea', cnName: '韩国' },
  { code: 'DE', name: 'Germany', cnName: '德国' },
  { code: 'FR', name: 'France', cnName: '法国' },
  { code: 'RU', name: 'Russia', cnName: '俄罗斯' },
  { code: 'CA', name: 'Canada', cnName: '加拿大' },
  { code: 'AU', name: 'Australia', cnName: '澳大利亚' },
  { code: 'SG', name: 'Singapore', cnName: '新加坡' },
  { code: 'IN', name: 'India', cnName: '印度' },
  { code: 'BR', name: 'Brazil', cnName: '巴西' },
  { code: 'IT', name: 'Italy', cnName: '意大利' },
  { code: 'ES', name: 'Spain', cnName: '西班牙' },
  { code: 'NL', name: 'Netherlands', cnName: '荷兰' },
  { code: 'SE', name: 'Sweden', cnName: '瑞典' },
  { code: 'CH', name: 'Switzerland', cnName: '瑞士' },
  { code: 'BE', name: 'Belgium', cnName: '比利时' },
  { code: 'AT', name: 'Austria', cnName: '奥地利' },
  { code: 'DK', name: 'Denmark', cnName: '丹麦' },
  { code: 'NO', name: 'Norway', cnName: '挪威' },
  { code: 'FI', name: 'Finland', cnName: '芬兰' },
  { code: 'IE', name: 'Ireland', cnName: '爱尔兰' },
  { code: 'NZ', name: 'New Zealand', cnName: '新西兰' },
  { code: 'HK', name: 'Hong Kong', cnName: '中国香港' },
  { code: 'TW', name: 'Taiwan', cnName: '中国台湾' },
  { code: 'MO', name: 'Macao', cnName: '中国澳门' },
  { code: 'MY', name: 'Malaysia', cnName: '马来西亚' },
  { code: 'TH', name: 'Thailand', cnName: '泰国' },
  { code: 'ID', name: 'Indonesia', cnName: '印度尼西亚' },
  { code: 'VN', name: 'Vietnam', cnName: '越南' },
  { code: 'PH', name: 'Philippines', cnName: '菲律宾' },
  { code: 'PK', name: 'Pakistan', cnName: '巴基斯坦' },
  { code: 'BD', name: 'Bangladesh', cnName: '孟加拉国' },
  { code: 'TR', name: 'Turkey', cnName: '土耳其' },
  { code: 'IR', name: 'Iran', cnName: '伊朗' },
  { code: 'SA', name: 'Saudi Arabia', cnName: '沙特阿拉伯' },
  { code: 'AE', name: 'United Arab Emirates', cnName: '阿联酋' },
  { code: 'IL', name: 'Israel', cnName: '以色列' },
  { code: 'ZA', name: 'South Africa', cnName: '南非' },
  { code: 'EG', name: 'Egypt', cnName: '埃及' },
  { code: 'NG', name: 'Nigeria', cnName: '尼日利亚' },
  { code: 'MX', name: 'Mexico', cnName: '墨西哥' },
  { code: 'AR', name: 'Argentina', cnName: '阿根廷' },
  { code: 'CL', name: 'Chile', cnName: '智利' },
  { code: 'CO', name: 'Colombia', cnName: '哥伦比亚' },
  { code: 'PE', name: 'Peru', cnName: '秘鲁' },
  { code: 'VE', name: 'Venezuela', cnName: '委内瑞拉' },
  { code: 'PL', name: 'Poland', cnName: '波兰' },
  { code: 'UA', name: 'Ukraine', cnName: '乌克兰' },
  { code: 'RO', name: 'Romania', cnName: '罗马尼亚' },
  { code: 'CZ', name: 'Czech Republic', cnName: '捷克' },
  { code: 'HU', name: 'Hungary', cnName: '匈牙利' },
  { code: 'GR', name: 'Greece', cnName: '希腊' },
  { code: 'PT', name: 'Portugal', cnName: '葡萄牙' },
  { code: 'KP', name: 'North Korea', cnName: '朝鲜' },
  { code: 'AF', name: 'Afghanistan', cnName: '阿富汗' },
  { code: 'IQ', name: 'Iraq', cnName: '伊拉克' },
  { code: 'SY', name: 'Syria', cnName: '叙利亚' },
  { code: 'CU', name: 'Cuba', cnName: '古巴' },
  // 可以在此添加更多国家
];
